version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-job:
    docker:
      - image: cimg/node:18.16.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run vercel-build

workflows:
  deploy-job:
    jobs:
      - build-job
